name: 'Build and Release Pipelines $(Date:yyyy-MM-dd)_v$(Rev:rr)'

pr: none
trigger: none
  # branches:
  #   include:
  #   - dev
  #   - main
  # paths:
  #   include:
  #   - 'service_principal'

    
variables: 
- group: 'service-connection'
- group: 'my_publicIP'
- name: system.debug
  value: 'true'
- name: RGName
  value: "rg-ADO-2"            
- name: StorageAccName
  value: "mystorageacct16425"  
- name: ContainerName
  value: "storage-container"         
- name: ADO_Environment
  value: "Staging"
- name: Pipeline_Agent
  value: 'My Agents'
- name: SKIPPED_CHECKS
  value: 'CKV_TF_1,CKV_AZURE_249'

<<<<<<< HEAD
  # Using tf-plan.yml or ci_template pipeline based on branch condition
stages: 
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  
  - template: pipeline_templates/tf-destroy.yml
    parameters:  
<<<<<<<< HEAD:azure-pipelines.yml
      TerraformDirectory: 'terraform'
      infrastructure: 'spn'
========
      TerraformDirectory: 'service_principal'
      infrastructure: 'spn_identity'
>>>>>>>> 8632c12 (fix: modify variable names, and update example.tf):service_principal/azure-pipelines.yml
      tfplan: 'spn.tfplan'
      BlobName: 'spn.tfstate'
- ${{ else }}:
  - template: pipeline_templates/tf-plan.yml
    parameters: 
<<<<<<<< HEAD:azure-pipelines.yml
      TerraformDirectory: 'terraform'
      infrastructure: 'spn'
      tfplan: 'spn.tfplan'
      BlobName: 'spn.tfstate'
  - template: pipeline_templates/tf-apply.yml
    parameters:  
      TerraformDirectory: 'terraform'
      infrastructure: 'spn'
========
      TerraformDirectory: 'service_principal'
      infrastructure: 'spn_identity'
>>>>>>>> 8632c12 (fix: modify variable names, and update example.tf):service_principal/azure-pipelines.yml
=======
  # Using build_template or ci_template pipeline based on branch condition
stages: 
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  
  - template: pipeline_templates/release_template.yml
    parameters:  
      TerraformDirectory: 'service_principal'
      infrastructure: 'spn_identity'
      tfplan: 'spn.tfplan'
      BlobName: 'spn.tfstate'
- ${{ else }}:
  - template: pipeline_templates/build_template.yml
    parameters: 
      TerraformDirectory: 'service_principal'
      infrastructure: 'spn_identity'
>>>>>>> ca9b2ccee3a82c3a350da8cf43ffc2ba10a60cdb
      tfplan: 'spn.tfplan'
      BlobName: 'spn.tfstate'